version: "3.7"

services:
  roadmapper-db:
    build: ./postgres
    container_name: roadmapper-db
    environment:
      - POSTGRES_DB=roadmapper-db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
    ports:
      - "5432:5432"

  roadmapper-server:
    container_name: roadmapper-server
    build:
      context: ./server
    volumes:
      - ".:/server"
      - "/server/node_modules"
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=test
      - KNEX_PORT=5432
      - KNEX_HOST=127.0.0.1
      - KNEX_DATABASE=roadmapper-db
      - KNEX_USER=testuser
      - KNEX_PASSWORD=testpassword
      - SERVER_PORT=5000

  roadmapper-frontend:
    container_name: roadmapper-frontend
    stdin_open: true
    build:
      context: ./frontend
    volumes:
      - ".:/frontend"
      - "/frontend/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
