version: "3.7"

services:
  roadmapper-database:
    build: ./postgres
    container_name: roadmapper-db
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=roadmapper-db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
    ports:
      - "5432:5432"
    volumes:
      - ./testdata/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  roadmapper-server:
    container_name: roadmapper-server
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - RDS_PORT=5432
      - RDS_HOST=roadmapper-database
      - RDS_DB_NAME=roadmapper-db
      - RDS_USERNAME=testuser
      - RDS_PASSWORD=testpassword
      - SESSION_SECRET=!top!secret!session!secret!
      - CORS_ORIGIN=http://localhost:3000
      - SERVER_PORT=5000

  roadmapper-frontend:
    container_name: roadmapper-frontend
    stdin_open: true
    build:
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=http://localhost:5000/
