export const english = {
  translation: {
    Home: 'Home',
    UserInfo: 'User Information',
    Close: 'Close',
    Save: 'Save',
    Add: 'Add',
    'Add new task': 'Add new task',
    'Add new milestone': 'Add new milestone',
    'Add new': 'Add new',
    'Task name': 'Task name',
    Description: 'Description',
    Tasks: 'Tasks',
    'Search for tasks': 'Search for tasks',
    'No tasks found': 'No tasks found',
    Login: 'Login',
    Username: 'Username',
    Password: 'Password',
    'Not logged in': 'Not logged in',
    'Invalid username or password': 'Invalid username or password',
    'How to rate?': 'How to rate?',
    'Sort by': 'Sort by',
    'Your ratings': 'Your ratings',
    "Team's overall ratings": "Team's overall ratings",
    'Not yet rated': 'Not yet rated:',
    Status: 'Status',
    'Required by': 'Required by',
    'Show all': 'Show all',
    'Not rated by me': 'Not rated by me',
    'Rated by me': 'Rated by me',
    'Created by': 'Created by',
    Completed: 'Completed',
    'Not completed': 'Not completed',
    'Rate task': 'Rate task',
    'Comment your rating...': 'Comment your rating...',
    'Please input a rating before submitting':
      'Please input a rating before submitting',
    Roadmap: 'Roadmap',
    'Roadmap View': 'Roadmap View',
    'task list': 'task list',
    Plan: 'Plan',
    Cancel: 'Cancel',
    'Overview for': 'Overview for',
    Logout: 'Logout',
    'Logging out': 'Logging out',
    'Ratings for': 'Ratings for',
    'Your rating': 'Your rating',
    'Your comment': 'Your comment',
    'You have not rated this task': 'You have not rated this task',
    "Team's ratings": "Team's ratings",
    'No ratings from team': 'No ratings from team',
    Rate: 'Rate',
    Title: 'Title',
    Rating: 'Rating',
    'Created on': 'Created on',
    Name: 'Name',
    Value: 'Value',
    'Rate customer': 'Rate customer',
    milestones: 'milestones',
    Milestones: 'Milestones',
    'Add milestone': 'Add milestone',
    'Milestone name': 'Milestone name',
    Stakeholders: 'Stakeholders',
    'Avg. Rating': 'Avg. Rating',
    'Your unrated tasks': 'Your unrated tasks',
    'Roadmap completion': 'Roadmap completion',
    Import: 'Import',
    'Import Jira tasks': 'Import Jira tasks',
    'Unassigned tasks': 'Unassigned tasks',
    "Time Estimation": "Time Estimation",
    "Estimate milestone durations": "Estimate milestone durations",
    "Milestone to compare with": "Milestone to compare with",
    "Select a milestone": "Select a milestone",
    "Unable to calculate work": "Unable to calculate work",
    "Predicted milestone durations": "Predicted milestone durations",
    "Set different weighing for clients": "Set different weighing for clients",
    "Client Weights": "Client Weights"
  },
};
