export const english = {
  translation: {
    Home: 'Home',
    UserInfo: 'User Information',
    Close: 'Close',
    Save: 'Save',
    Add: 'Add',
    'Add new task': 'Add new task',
    'Task name': 'Task name',
    Description: 'Description',
    'Task List': 'Task list',
    'Search for tasks': 'Search for tasks',
    'Task description': 'Task description',
    'No tasks found': 'No tasks found',
    Login: 'Login',
    Username: 'Username',
    Password: 'Password',
    'Not logged in': 'Not logged in',
    'Invalid username or password': 'Invalid username or password',
    'How to rate?': 'How to rate?',
    'Sort by': 'Sort by',
    'Your ratings': 'Your ratings',
    "Team's overall ratings": "Team's overall ratings",
    'Not yet rated': 'Not yet rated:',
    Status: 'Status',
    'Required by': 'Required by',
    'Show all': 'Show all',
    'Not rated by me': 'Not rated by me',
    'Rated by me': 'Rated by me',
    'Created at': 'Created at',
    'Created by': 'Created by',
    Completed: 'Completed',
    'Not completed': 'Not completed',
    'Rate task': 'Rate task',
    'Comment your rating...': 'Comment your rating...',
    'Please input a rating before submitting':
      'Please input a rating before submitting',
    Roadmap: 'Roadmap',
    'Roadmap View': 'Roadmap View',
    'task list': 'task list',
    Planner: 'Planner',
    Cancel: 'Cancel',
    'Overview for': 'Overview for',
    Logout: 'Logout',
    'Logging out': 'Logging out',
    'Ratings for': 'Ratings for',
    'Your rating': 'Your rating',
    'Your comment': 'Your comment',
    'You have not rated this task': 'You have not rated this task',
    "Team's ratings": "Team's ratings",
    'No ratings from team': 'No ratings from team',
  },
};
