#!/bin/bash
set -e

cd /var/app/server

AWS_SECRET1_ID="staging/backendEnvVariables"
AWS_RDS_SECRET_ID="staging/backendRdsCredentials"
AWS_REGION="eu-central-1"
ENVFILE=".env"

# Export the secret to .env
{
  aws secretsmanager get-secret-value --secret-id $AWS_SECRET1_ID --region $AWS_REGION | \
    jq -r '.SecretString | fromjson | to_entries[] | "\(.key)=\(.value)"'
  aws secretsmanager get-secret-value --secret-id $AWS_RDS_SECRET_ID --region $AWS_REGION | \
    jq -r '.SecretString | fromjson | to_entries[] | "RDS_\(.key|ascii_upcase)=\(.value)"'
} > $ENVFILE

# Copy env to build for knex commands to recognize it
cp $ENVFILE ./build/server/$ENVFILE

pm2 start yarn --name backend -- start-prod
