#!/bin/bash
set -e

cd /var/app/server

if [ "$DEPLOYMENT_GROUP_NAME" == "StagingBackendDeploymentGroup" ]
then
    AWS_SECRET1_ID="actuallyStaging/backendEnvVariables"
    AWS_RDS_SECRET_ID="actuallyStagingDb/backendRdsCredentials"
    AWS_REGION="eu-central-1"
    ENVFILE=".env"
fi

if [ "$DEPLOYMENT_GROUP_NAME" == "BackendDeploymentGroup" ]
then
    AWS_SECRET1_ID="staging/backendEnvVariables"
    AWS_RDS_SECRET_ID="staging/backendRdsCredentials"
    AWS_REGION="eu-central-1"
    ENVFILE=".env"
fi


# Export the secret to .env
{
  aws secretsmanager get-secret-value --secret-id $AWS_SECRET1_ID --region $AWS_REGION | \
    jq -r '.SecretString | fromjson | to_entries[] | "\(.key)=\(.value)"'
  aws secretsmanager get-secret-value --secret-id $AWS_RDS_SECRET_ID --region $AWS_REGION | \
    jq -r '.SecretString | fromjson | to_entries[] | "RDS_\(.key|ascii_upcase)=\(.value)"'
} > $ENVFILE

# Copy env to build for knex commands to recognize it
cp $ENVFILE ./build/server/$ENVFILE

pm2 start yarn --name backend -- start-prod
