name: Continuous integration
on: push
jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        env:
          POSTGRES_DB: "roadmapper-db"
          POSTGRES_USER: "testuser"
          POSTGRES_PASSWORD: "testpassword"

        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: cd server && yarn install --frozen-lockfile && yarn test
        env:
          POSTGRES_DB: "roadmapper-db"
          POSTGRES_USER: "testuser"
          POSTGRES_PASSWORD: "testpassword"
          NODE_ENV: "test"
          RDS_PORT: "5432"
          RDS_HOSTNAME: "localhost"
          RDS_DB_NAME: "roadmapper-db"
          RDS_USERNAME: "testuser"
          RDS_PASSWORD: "testpassword"
          SESSION_SECRET: "!top!secret!session!secret!"
          CORS_ORIGIN: "http://localhost:3000"
          SERVER_PORT: "5000"
          CHOKIDAR_USEPOLLING: "true"
          REACT_APP_API_BASE_URL: "http://localhost:5000/"
          JIRA_CONSUMER_KEY: "roadmapper"
